version: "3.8"
services:
    db:
        image: postgres:14.6
        environment:
            POSTGRES_USER: secretariat
            POSTGRES_PASSWORD: secretariat
            POSTGRES_DB: secretariat
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "secretariat"]
            interval: 5s
            timeout: 5s
            retries: 5

    maildev:
        image: maildev/maildev:2.0.5
        platform: linux/arm64
        command: bin/maildev --smtp 1025 --web 1080 --hide-extensions STARTTLS
        ports:
            - "1025:1025"
            - "1080:1080"
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:1080"]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    memory: 256M
                reservations:
                    memory: 128M

    redis:
        image: redis:alpine
        command: redis-server --requirepass localpwd
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "localpwd", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    web:
        build:
            context: .
            target: production
        platform: linux/arm64
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
            maildev:
                condition: service_healthy
        env_file:
            - .env
        environment:
            NODE_ENV: production
            DATABASE_URL: postgresql://secretariat:secretariat@db:5432/secretariat
            NEXTAUTH_DATABASE_URL: postgresql://secretariat:secretariat@db:5432/nextauth
            REDIS_URL: redis://:localpwd@redis:6379
            MAIL_HOST: maildev
            MAIL_PORT: 1025
            MAIL_IGNORE_TLS: "true"
        ports:
            - "8100:8100"
        restart: on-failure

volumes:
    postgres_data:
    redis_data:
