version: "3"
services:
    db:
        image: postgres:14.6
        environment:
            POSTGRES_USER: secretariat
            POSTGRES_PASSWORD: secretariat
        ports:
            - "5432:5432"
    maildev:
        image: maildev/maildev:2.0.5
        platform: linux/arm64
        command: bin/maildev --smtp 1025 --web 1080 --hide-extensions STARTTLS
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:1080"]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    memory: 256M
                reservations:
                    memory: 128M
    redis:
        image: redis:alpine
        command: redis-server --requirepass localpwd
        hostname: redis
        restart: always
        ports:
            - 6379:6379
    web:
        build: .
        platform: linux/arm64
        command: bash -c "npm run migrate && node --max_old_space_size=8192 --inspect=0.0.0.0:9230 -r ts-node/register src/server/server.ts"
        depends_on:
            - db
            - maildev
            - redis
        env_file:
            - .env
        environment:
            CHAT_WEBHOOK_URL_GENERAL: "https://example.com"
            CHAT_WEBHOOK_URL_SECRETARIAT: "https://example.com"
            CHAT_WEBHOOK_URL_DINUM: "https://example.com"
            CHAT_WEBHOOK_URL_GIP: "https://example.com"
        ports:
            - "8100:8100"
            - "9230:9230"
        volumes:
            - .:/app
        restart: on-failure
