version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - .next:/app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_OPTIONS=--max_old_space_size=8192
      - DATABASE_URL=postgresql://secretariat:secretariat@db:5432/secretariat
      - NEXTAUTH_DATABASE_URL=postgresql://secretariat:secretariat@db:5432/nextauth
      - REDIS_URL=redis://:localpwd@redis:6379
      - MAIL_HOST=maildev
      - MAIL_PORT=1025
      - MAIL_IGNORE_TLS=true
      - SEED_FAKE_DATA=true
      # Development secrets (do not use in production)
      - NEXTAUTH_SECRET=local-development-secret-do-not-use-in-production
      - NEXTAUTH_URL=http://localhost:8100
      # Chat webhooks for development
      - CHAT_WEBHOOK_URL_GENERAL=http://localhost:8100/api/chat/webhook/general
      - CHAT_WEBHOOK_URL_SECRETARIAT=http://localhost:8100/api/chat/webhook/secretariat
      - CHAT_WEBHOOK_URL_DINUM=http://localhost:8100/api/chat/webhook/dinum
      - CHAT_WEBHOOK_URL_GIP=http://localhost:8100/api/chat/webhook/gip
    ports:
      - "8100:8100"
      - "9229:9229"
    restart: unless-stopped

  db:
    environment:
      - POSTGRES_DB=secretariat

volumes:
  postgres_data:
  redis_data:
