export const thematiques = [
    "Administratif",
    "Agriculture",
    "Collectivités",
    "Démocratie",
    "Écologie",
    "Entreprises",
    "Formation",
    "Inclusion numérique",
    "Jeunesse",
    "Justice",
    "Logement",
    "Mer",
    "Open-Data",
    "Outil technique",
    "Patrimoine",
    "Santé",
    "Sécurité informatique",
    "Social",
    "Territoires",
    "Transports",
    "Travail / Emploi",
];
