// https://github.com/betagouv/secretariat/issues/247
// todo
export const employers = [
    "Agglomération de Pau Béarn Pyrénées",
    "Arolla",
    "captive",
    "CGET",
    "cnamts",
    "Codeurs en Liberté",
    "Cour des comptes",
    "département du Nord",
    "Département du Pas-de-Calais",
    "département du Val-d'Oise",
    "DGCCRF",
    "DGE",
    "dila",
    "DINUM",
    "DIRECCTE",
    "DJEPVA",
    "drjscs",
    "Éducation Nationale",
    "EIG",
    "EY",
    "ICC",
    "INOPS",
    "Ippon/LLL",
    "KeiruaProd",
    "LaZone / ScopyLeft",
    "MAS",
    "Ministère de l'Intérieur",
    "Ministère de la Culture",
    "Ministère des affaires étrangères",
    "Ministère des Affaires Sociales",
    "Ministère des Armées",
    "MTES",
    "NUMA",
    "OCTO",
    "pass-culture",
    "Pole Emploi",
    "Région Bretagne",
    "Réseau Canopé",
    "Scopyleft",
    "Sogilis Lyon",
    "UT7",
] as [string, ...string[]]; // TODO: ??
