name: cron

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Get changed files
        id: changed-files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          changed=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)
          echo "Changed files:"
          echo "$changed"
          # Don't replace newlines — preserve them
          echo "changed_files<<EOF" >> "$GITHUB_OUTPUT"
          echo "$changed" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Check if cron or schedule file changed
        id: check_diff
        run: |
          changed="false"
          while IFS= read -r file; do
            if [[ "$file" == "src/server/schedulers/cron.ts" || "$file" == "src/server/queueing/schedule.ts" ]]; then
              changed="true"
              break
            fi
          done <<< "${{ steps.changed-files.outputs.changed_files }}"
      
          echo "changed=$changed" >> "$GITHUB_OUTPUT"

      - name: Set up Node.js
        if: steps.check_diff.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        if: steps.check_diff.outputs.changed == 'true'
        run: npm install

      - name: Generate CRON.md
        if: steps.check_diff.outputs.changed == 'true'
        env:
          REDIS_URL: "dummy-url"
          SESSION_SECRET: "dummy-secret"
          CHAT_WEBHOOK_URL_SECRETARIAT: "dummy-url"
          CHAT_WEBHOOK_URL_GENERAL: "dummy-url"
          CHAT_WEBHOOK_URL_DINUM: "dummy-url"
          CHAT_WEBHOOK_URL_GIP: "dummy-url"
          MAILING_LIST_NEWSLETTER: 0
          OVH_APP_KEY: fakeovhkey
          OVH_APP_SECRET: fakeovhsecret
          OVH_CONSUMER_KEY: fakeconsumerkey
        run: npx ts-node generate-cron-md.ts

      - name: Commit and push changes
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CRON.md
          git diff --cached --quiet || git commit -m "Update CRON.md due to scheduler file change [skip ci]"
          git push origin HEAD:${{ github.head_ref }}
