name: Auto Commit on Scheduler File Change

on:
    push:
        branches:
            - main

jobs:
    auto-commit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18 # or whatever version you're using

            - name: Install dependencies
              run: npm install

            - name: Check if scheduler file changed
              id: check_diff
              run: |
                  if git diff --name-only HEAD^ HEAD | grep -qE 'src/server/schedulers/cron.ts'; then
                    echo "changed=true" >> "$GITHUB_OUTPUT"
                  else
                    echo "changed=false" >> "$GITHUB_OUTPUT"
                  fi

            - name: Generate CRON.md
              if: steps.check_diff.outputs.changed == 'true'
              run: npx ts-node scripts/generate-cron-md.ts

            - name: Commit and push changes
              if: steps.check_diff.outputs.changed == 'true'
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add CRON.md
                  git diff --cached --quiet || git commit -m "Update CRON.md due to scheduler file change"
                  git push
