name: Validate Zod Schema

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    validate-schema:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Check if checklist file changed
              id: check_diff
              run: |
                  if git diff --name-only HEAD^ HEAD | grep -qE 'public/onboarding/checklist.yml'; then
                    echo "changed=true" >> "$GITHUB_OUTPUT"
                  else
                    echo "changed=false" >> "$GITHUB_OUTPUT"
                  fi

            - name: Set up Node.js
              if: steps.check_diff.outputs.changed == 'true'
              uses: actions/setup-node@v3
              with:
                  node-version: "16" # Specify the version you need

            - name: Install dependencies
              if: steps.check_diff.outputs.changed == 'true'
              run: |
                  npm install

            - name: Validate file against Zod schema
              if: steps.check_diff.outputs.changed == 'true'
              run: node .github/workflows/utils/validateFile.js
