name: Playwright Tests

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    e2e:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres
            ports: ["5432:5432"]
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            env:
              POSTGRES_PASSWORD: postgres
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Setup the database
              run: |
                npm run migrate
                npm run seed
              env:
                  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
                  HASH_SALT: fakesaltfortestenv
            - name: Setup the app
              run: npm run build
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Launch playwright
              run: |
                  npx playwright test
              env:
                  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
                  HOSTNAME: localhost:8100
                  OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
                  OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
                  OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
                  PROTECTED_API_KEYS: test-api-key
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 3
