name: Playwright Tests

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    e2e:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres
            ports: ["5432:5432"]
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            env:
              POSTGRES_PASSWORD: postgres
          maildev:
            image: maildev/maildev
            ports: ["1080:80", "11025:25"]
            env:
              MAILDEV_INCOMING_USER: mailuser
              MAILDEV_INCOMING_PASS: mailpassword
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Setup the database
              run: |
                npm run migrate
                npm run seed
              env:
                  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
                  HASH_SALT: fakesaltfortestenv
            - name: Setup the app
              run: npm run build
              env:
                CI: true
                FEATURE_SHOULD_SEND_MESSAGE_TO_AUTHOR: true
                NEWSLETTER_HASH_SECRET: fakenewslettersecret
                SHOULD_SEND_NL: true
                OVH_APP_KEY: fakeovhkey
                OVH_APP_SECRET: fakeovhsecret
                OVH_CONSUMER_KEY: fakeconsumerkey
                SESSION_SECRET: fakesessionsecret
                CHAT_WEBHOOK_URL_SECRETARIAT: https://example.com
                CHAT_WEBHOOK_URL_GENERAL: https://example.com
                CHAT_WEBHOOK_URL_DINUM: https://example.com
                CHAT_WEBHOOK_URL_GIP: https://example.com
                MATTERMOST_BOT_TOKEN: faketoken
                MATTERMOST_INVITE_ID: fakeid
                MAIL_PASS: fakepass
                MAIL_USER: fakeuser
                MAIL_SENDER: fake@localhost
                DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
                HOSTNAME: localhost:8100
                HASH_SALT: fakesaltfortestenv
                GITHUB_FORK: dummy-github-fork
                MAILING_LIST_NEWSLETTER: 0
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Launch playwright
              run: npx playwright test
              env:
                CI: true
                FEATURE_SHOULD_SEND_MESSAGE_TO_AUTHOR: true
                NEWSLETTER_HASH_SECRET: fakenewslettersecret
                SHOULD_SEND_NL: true
                OVH_APP_KEY: fakeovhkey
                OVH_APP_SECRET: fakeovhsecret
                OVH_CONSUMER_KEY: fakeconsumerkey
                SESSION_SECRET: fakesessionsecret
                CHAT_WEBHOOK_URL_SECRETARIAT: https://example.com
                CHAT_WEBHOOK_URL_GENERAL: https://example.com
                CHAT_WEBHOOK_URL_DINUM: https://example.com
                CHAT_WEBHOOK_URL_GIP: https://example.com
                MATTERMOST_BOT_TOKEN: faketoken
                MATTERMOST_INVITE_ID: fakeid
                MAIL_PASS: fakepass
                MAIL_USER: fakeuser
                MAIL_SENDER: fake@localhost
                DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
                HOSTNAME: localhost:8100
                HASH_SALT: fakesaltfortestenv
                GITHUB_FORK: dummy-github-fork
                MAILING_LIST_NEWSLETTER: 0
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 3
