name: Playwright Tests
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    e2e:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.10.0
            - name: Install dependencies
              run: |
                  npm ci
                  npx playwright install --with-deps
            - name: Start local environment
              run: |
                  cp .env.test .env
                  docker compose up -d
                  sleep 15
                  yarn migrate
                  yarn seed
                  yarn build
                  yarn start &
              env:
                  OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
                  OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
                  OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
                  PROTECTED_API_KEYS: test-api-key
            - name: Wait
              uses: cygnetdigital/wait_for_response@v2.0.0
              with:
                  url: "http://localhost:8100/"
                  responseCode: "200"
                  timeout: 120000
                  interval: 500
            - name: Launch playwright
              run: |
                  npx playwright test
              env:
                  HOSTNAME: localhost:8100

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 3
